# Generated by Django 4.1.2 on 2022-10-10 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylehub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_choice', models.CharField(blank=True, choices=[('Top', (('button-down', 'Button-down'), ('dress', 'Dress'), ('shirt', 'Shirt'), ('sweater', 'Sweater'), ('t-shirt', 'T-shirt'))), ('Bottom', (('pants', 'Pants'), ('shorts', 'Shorts'), ('skirt', 'Skirt'))), ('Outwear', (('cardigan', 'Cardigan'), ('coat', 'Coat'), ('jacket', 'Jacket'), ('vest', 'Vest'))), ('Shoes', (('boots', 'Boots'), ('flats', 'Flats'), ('heels', 'Heels'), ('sandals', 'Sandals'), ('slippers', 'Slippers'), ('sneakers', 'Sneakers')))], max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=25, null=True)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='closet_items')),
                ('added_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('tag', models.CharField(max_length=50)),
                ('outfit_date', models.DateField(blank=True, null=True)),
                ('outfit_image', models.ImageField(blank=True, null=True, upload_to='outfits')),
                ('draft', models.BooleanField(default=True)),
                ('favorite', models.BooleanField(default=False)),
                ('closet_item', models.ManyToManyField(to='stylehub.closetitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='closetitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closet_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
