# Generated by Django 4.0 on 2022-10-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylehub', '0002_alter_customuser_groups_and_more'),
        ('stylehub', '0002_closetitem_customuser_bio_customuser_profile_image_and_more'),
    ]

    operations = [
    ]
