# Generated by Django 4.0 on 2022-10-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylehub', '0003_merge_20221011_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='closet_item',
            field=models.ManyToManyField(to='stylehub.ClosetItem'),
        ),
    ]
