# Generated by Django 4.0 on 2022-10-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylehub', '0004_alter_outfit_closet_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closetitem',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='closet_items/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='outfit_image',
            field=models.ImageField(blank=True, null=True, upload_to='outfits/'),
        ),
    ]
