# Generated by Django 4.0 on 2022-10-11 19:38

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('stylehub', '0005_alter_closetitem_item_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closetitem',
            name='tag',
        ),
        migrations.AddField(
            model_name='closetitem',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='tag',
        ),
        migrations.AddField(
            model_name='outfit',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
