# Generated by Django 4.0 on 2022-10-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylehub', '0006_remove_closetitem_tag_closetitem_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='closet_item',
            field=models.ManyToManyField(related_name='outfits', to='stylehub.ClosetItem'),
        ),
    ]
