# Generated by Django 4.0 on 2022-10-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylehub', '0007_alter_outfit_closet_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closetitem',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow'), ('green', 'Green'), ('turqoise', 'Turqoise'), ('blue', 'Blue'), ('purple', 'Purple'), ('red', 'Red'), ('pink', 'Pink'), ('orange', 'Orange'), ('brown', 'Brown'), ('grey', 'GREY'), ('multi', 'Multi')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='closetitem',
            name='source',
            field=models.CharField(blank=True, choices=[('thrift_shop', 'Thrift Shop'), ('resale/consignment_shop', 'Resale/Consignment Shop'), ('friend', 'Friend'), ('discount_store', 'Discount Store'), ('department_store', 'Department Store'), ('brand_store', 'Brand Store'), ('purple', 'Purple'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
