# Generated by Django 4.0 on 2022-10-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylehub', '0008_alter_closetitem_color_alter_closetitem_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closetitem',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow'), ('green', 'Green'), ('turqoise', 'Turqoise'), ('blue', 'Blue'), ('purple', 'Purple'), ('red', 'Red'), ('pink', 'Pink'), ('orange', 'Orange'), ('brown', 'Brown'), ('grey', 'Grey'), ('multi', 'Multi')], max_length=25, null=True),
        ),
    ]
