# Generated by Django 4.0 on 2022-10-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylehub', '0009_alter_closetitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closetitem',
            name='color',
            field=models.CharField(blank=True, choices=[('green', 'Green'), ('turqoise', 'Turqoise'), ('blue', 'Blue'), ('purple', 'Purple'), ('red', 'Red'), ('pink', 'Pink'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('white', 'White'), ('grey', 'Grey'), ('black', 'Black'), ('brown', 'Brown'), ('multi', 'Multi')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='closetitem',
            name='source',
            field=models.CharField(blank=True, choices=[('brand_store', 'Brand Store'), ('department_store', 'Department Store'), ('discount_store', 'Discount Store'), ('thrift_shop', 'Thrift Shop'), ('resale/consignment_shop', 'Resale/Consignment Shop'), ('friend', 'Friend'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
