# Generated by Django 4.0 on 2022-10-15 15:46

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('stylehub', '0010_alter_closetitem_color_alter_closetitem_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagClosetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagOutfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='closetitem',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='tag',
        ),
        migrations.AddField(
            model_name='closetitem',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='stylehub.TagClosetItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='stylehub.TagOutfit', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='tagoutfit',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylehub.outfit'),
        ),
        migrations.AddField(
            model_name='tagoutfit',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
        migrations.AddField(
            model_name='tagclosetitem',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylehub.closetitem'),
        ),
        migrations.AddField(
            model_name='tagclosetitem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
    ]
