# Generated by Django 4.0 on 2022-10-15 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylehub', '0011_alter_closetitem_brand_alter_closetitem_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='favorite',
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='stylehub.outfit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='stylehub.customuser')),
            ],
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', ''), name='unique_for_question_and_user'),
        ),
    ]
