# Generated by Django 4.0 on 2022-10-18 16:05

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stylehub', '0011_alter_closetitem_brand_alter_closetitem_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closetitem',
            name='item_image',
        ),
        migrations.AddField(
            model_name='closetitem',
            name='item_image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='closet_items/'),
        ),
    ]
