# Generated by Django 4.0 on 2022-10-15 16:14

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('stylehub', '0011_tagclosetitem_tagoutfit_remove_closetitem_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericStringTaggedClosetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=50, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericStringTaggedOutfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=50, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tagoutfit',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='tagoutfit',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='closetitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='closetitem',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='id',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='tags',
        ),
        migrations.AddField(
            model_name='closetitem',
            name='closet_item_id',
            field=models.CharField(default=True, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='closetitem',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='stylehub.GenericStringTaggedClosetItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='outfit_id',
            field=models.CharField(default=True, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='outfit',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='stylehub.GenericStringTaggedOutfit', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='TagClosetItem',
        ),
        migrations.DeleteModel(
            name='TagOutfit',
        ),
    ]
