# Generated by Django 4.0 on 2022-10-18 16:12

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('stylehub', '0011_alter_closetitem_brand_alter_closetitem_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closetitem',
            name='item_choice',
        ),
        migrations.AddField(
            model_name='closetitem',
            name='category',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('outerwear', 'Outerwear'), ('shoes', 'Shoes')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='closetitem',
            name='subcategory',
            field=models.CharField(choices=[('button-down', 'Button-down'), ('dress', 'Dress'), ('shirt', 'Shirt'), ('sweater', 'Sweater'), ('t-shirt', 'T-shirt'), ('pants', 'Pants'), ('shorts', 'Shorts'), ('skirt', 'Skirt'), ('cardigan', 'Cardigan'), ('coat', 'Coat'), ('jacket', 'Jacket'), ('vest', 'Vest'), ('boots', 'Boots'), ('flats', 'Flats'), ('heels', 'Heels'), ('sandals', 'Sandals'), ('slippers', 'Slippers'), ('sneakers', 'Sneakers')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='closetitem',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink'), ('purple', 'Purple'), ('turqoise', 'Turqoise'), ('blue', 'Blue'), ('brown', 'Brown'), ('black', 'Black'), ('grey', 'Grey'), ('multi', 'Multi')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='closetitem',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
