# Generated by Django 4.0 on 2022-10-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylehub', '0014_alter_outfit_draft'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='outfit',
            constraint=models.UniqueConstraint(condition=models.Q(('draft', True)), fields=('user', 'draft'), name='unique_draft'),
        ),
    ]
